version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/:/usr/src/app
    entrypoint: [ "perl", "/usr/src/app/app.pl" ]
    # entrypoint: ["perl", "./migrations/migrate.pl"]
    depends_on:
      - pgbase
      - redis

  pgbase:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 225388
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
