version: '3'
services:

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - pgbase
      - redis
    environment:
      - DATABASE_HOST=pgbase
      - REDIS_HOST=redis
      - SMTP_HOST=mail.nic.ru
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_password
    volumes:
      - .:/usr/src/app
    command: ["perl", "./migrations/migrate.pl"]

  pgbase:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 225388
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
